controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - segment_central_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: cart_imu_sensor
    frame_id: imu
# controller_manager:
#   ros__parameters:
#     update_rate: 100  # Hz

#     gripper_controller:
#       type: forward_command_controller/ForwardCommandController

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

# gripper_controller:
#   ros__parameters:
#     joints:
#       - my_pivot_joint
#     interface_name: position

