name: Federer_verification

on:
  pull_request:
    branches: [ main, devel, functions_devel ]
  push:
    branches: [ main, devel, functions_devel ]

jobs:
  build_ws:
    runs-on: ubuntu-20.04
    steps:
      - uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: foxy
      - uses: ros-tooling/action-ros-ci@0.2.7
        with:
          target-ros2-distro: foxy