name: Federer_verification

on:
  pull_request:
    branches: [ main, devel, functions_devel ]
  push:
    branches: [ main, devel, functions_devel ]

jobs:
  build_ws:
    runs-on: ubuntu-20.04
    steps:
      - uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: foxy
      - uses: ros-tooling/action-ros-ci@0.2.7
        with:
          target-ros2-distro: foxy
          package-name: bot_control
          skip-tests: true
      - uses: ros-tooling/action-ros-ci@0.2.7
        with:
          target-ros2-distro: foxy
          package-name: guidage_pkg
          skip-tests: true
      - uses: ros-tooling/action-ros-ci@0.2.7
        with:
          target-ros2-distro: foxy
          package-name: process_camera_pkg
          skip-tests: true
      - uses: ros-tooling/action-ros-ci@0.2.7
        with:
          target-ros2-distro: foxy
          package-name: remote_controller_pkg
          skip-tests: true
      - uses: ros-tooling/action-ros-ci@0.2.7
        with:
          target-ros2-distro: foxy
          package-name: robot_description
          skip-tests: true
      - uses: ros-tooling/action-ros-ci@0.2.7
        with:
          target-ros2-distro: foxy
          package-name: tennis_court
          skip-tests: true

      # - name: 'Run PEP8'
      #   uses: quentinguidee/pep8-action@v1
      #   with:
      #     arguments: '--max-line-length=120'